# hiltichallenge2021, stereo camera configuration

#==============#
# Camera Model #
#==============#

Camera:
  name: "Hilti Challenge 2021 stereo camera"
  setup: "stereo"
  model: "perspective"

  # K: [611.9695434570312, 0.0, 318.71343994140625, 0.0, 612.0466918945312, 237.70240783691406, 0.0, 0.0, 1.0]
  fx: 611.9695434570312
  fy: 612.0466918945312
  cx: 318.71343994140625
  cy: 237.70240783691406

  # D: [0.0, 0.0, 0.0, 0.0, 0.0]
  k1: 0
  k2: 0
  p1: 0
  p2: 0
  k3: 0

  fps: 10.0
  cols: 1440
  rows: 1080
  # 50mm baseline for the D435i
  focal_x_baseline: 30.598477150000004

  color_order: "RGB"


#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  max_num_keypoints: 1000
  ini_max_num_keypoints: 2000
  depth_threshold: 200.0
  depthmap_factor: 1000.0

#================#
# ORB Parameters #
#================#

Feature:
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.05
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.9
  viewpoint_z: -1.9
  viewpoint_f: 400
